# Application name
name: Election 2020

# API endpoint
api: "http://localhost:8000"

# Application layout configuration
layout:
  description: >
    # Election 2020

    *Disclaimer: This is for demonstration purposes only. There will be errors based on the nuances of the English language
    and personal perception. Users should judge the accuracy of results for themselves. All titles and links are displayed as is from Reddit.
    Users agree to use their own discretion and accept responsibility for the links they click.*
      
    This application categorizes 2020 US Presidential Election Reddit post titles by topic, objectivity and potential bias
    towards a candidate. Data is pulled via the Reddit API using a series of queries for popular link posts. In many but not all cases,
    the titles of these posts are headlines for news articles.
      
    Reddit post titles are labeled using two categories:
      
      - Objectivity  
      - Bias towards a candidate  
       
    Generally, as the objectivity score increases, the level of bias should decrease.
       
    ### Tech stack
      
    A zero-shot classifier, backed by a large general language model with no labeled data, is used to categorize topics,
    objectivity and potential bias. Additionally, a txtai index enables ad hoc similarity searches against the data.
      
    The following libraries are used:

      - txtai
      - Transformers
      - Sentence Transformers
      - Streamlit
      - FastAPI
       
    [Full source code and configuration](https://github.com/neuml/tldrstory)

  queries:
    name: Issues
    values: [Latest, --Search--, Economy, Health Care, Supreme Court, Coronavirus, Violent Crime, Foreign Policy, Gun Policy,
             Race Relations, Immigration, Climate Change, Abortion]
 
  filters: [Objective, Bias]

  chart:
    name: Candidate Bias
    x: Bias
    y: Objective
    scale: [0, 4.5, 5.0, 5.5, 10]
    colors: ["#1976D2", "#64B5F6", "#9575CD", "#E57373", "#D32F2F"]

  table:
    Objective:
    Bias: 
      - [0, 3.0, Strong Biden, "color: #1E88E5; font-weight: bold"]
      - [3.0, 4.5, Lean Biden, "color: #1E88E5"]
      - [4.5, 5.5, Neutral, "color: #7E57C2"]
      - [5.5, 7.0, Lean Trump, "color: #E35935"]
      - [7.0, 10.0, Strong Trump, "color: #E35935; font-weight: bold"]
